import { Metadata } from 'next';

export const generateMetadata = (): Metadata => {
  return {
    title: "Find Jobs in Sydney & Newcastle | Job4Online",
    description: "Discover job opportunities in Sydney and Newcastle with Job4Online. Search, apply, and connect with employers for your next career move.",
    keywords: [
      "jobs in Australia",
      "Australian job site",
      "find jobs Australia",
      "career opportunities Australia",
      "job search Australia",
      "employment Australia",
      "hiring in Australia",
      "recruitment Australia",
      "jobs in Sydney",
      "jobs in Newcastle",
      "Sydney job search",
      "Newcastle job vacancies",
      "career opportunities in Sydney",
      "career opportunities in Newcastle",
      "kitchen jobs in Australia",
      "hospitality jobs in Australia",
      "retail jobs in Australia",
      "chef jobs in Australia",
      "cook jobs in Australia",
      "waiter jobs in Australia",
      "waitress jobs in Australia",
      "kitchen jobs in Sydney",
      "hospitality jobs in Sydney",
      "retail jobs in Sydney",
      "chef jobs in Sydney",
      "cook jobs in Sydney",
      "waiter jobs in Sydney",
      "waitress jobs in Sydney",
      "kitchen jobs in Newcastle",
      "hospitality jobs in Newcastle",
      "retail jobs in Newcastle",
      "chef jobs in Newcastle",
      "cook jobs in Newcastle",
      "waiter jobs in Newcastle",
      "waitress jobs in Newcastle",
    ],
    authors: [{ name: "Job4Online", url: "https://job4online.com.au" }],
    openGraph: {
      title: "Find Jobs in Sydney & Newcastle | Job4Online",
      description: "Discover job opportunities in Sydney and Newcastle with Job4Online. Search, apply, and connect with employers for your next career move.",
      url: "https://job4online.com.au",
      siteName: "Job4Online",
      images: [
        {
          url: "https://job4online.com.au/og-image.jpg",
          width: 1200,
          height: 630,
          alt: "Job4Online - Find Jobs in Sydney & Newcastle",
        },
      ],
      locale: "en_AU",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "Find Jobs in Sydney & Newcastle | Job4Online",
      description: "Discover job opportunities in Sydney and Newcastle with Job4Online. Search, apply, and connect with employers for your next career move.",
      images: ["https://job4online.com.au/twitter-image.jpg"],
    },
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    icons: {
      icon: "/favicon.ico",
      shortcut: "/shortcut-icon.png",
      apple: "/apple-touch-icon.png",
    },
    // manifest: "https://job4online.com.au/site.webmanifest",
    // metadataBase: new URL("https://job4online.com.au"),
    alternates: {
      canonical: "/",
    },
  };
};
